apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: pythonrocks/flask
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000
